version: "3.9"

services:
  kicad:
    image: kicad/kicad:9.0-full
    container_name: kicad
    user: "${UID}:${GID}"
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${HOME}/kicad:/home/kicad/projects
    command: kicad
    network_mode: host
    ipc: host
    tty: true
    stdin_open: true

